name: Deploy to GitHub Pages

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Sets up Node.js environment
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.1.0
        with:
          node-version: '20.x'
          architecture: 'x64'
          check-latest: true
          cache: 'npm'
          cache-dependency-path: 'package.json'
          registry-url: 'https://registry.npmjs.org'

      # Generate package-lock.json
      - name: Generate package-lock.json
        run: |
          npm install --package-lock-only
          echo "Generated package-lock.json"

      # Clean install dependencies
      - name: Install Dependencies
        run: |
          npm ci
          echo "Dependencies installed successfully"

      # Build the project
      - name: Build Project
        run: |
          npm run build
          echo "Build completed successfully"

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: build
          token: ${{ secrets.GITHUB_TOKEN }}